### ISSUE TITLE
atom-clock throws errors after upgrade to babel 6

### ISSUE THREAD

**Issue by Ben3eeE** [b3by/atom-clock#18]
We have upgraded babel in Atom core(https://github.com/atom/atom/pull/13823) and noticed that your package is no longer working after these changes, in particular we found the following error when starting Atom master `1.16.0-dev-02a1010`:

```
Failed to activate the status-bar package
contentWidth is not defined
ReferenceError: contentWidth is not defined
    at AtomClockView.adjustElementSize (atom-clock-view.js:97:5)
    at AtomClockView.initialize (atom-clock-view.js:21:10)
    at AtomClockView.start (atom-clock-view.js:14:10)
    at Object.consumeStatusBar (atom-clock.js:45:24)
    at Provider.module.exports.Provider.provide (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\node_modules\service-hub\lib\provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\node_modules\service-hub\lib\service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package.js:396:71)
    at Package.module.exports.Package.activateNow (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package.js:221:16)
    at C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package.js:96:15)
    at C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-49ec99d\resources\app.asar\src\atom-environment.js:812:28
```

To ensure your package keeps working after we will release the aforementioned pull request, please make sure to fix these errors and publish a new version.

Please, let me know if you have any questions or concerns and if I can help somehow. Thanks!

/cc: @as-cii

**Comment by b3by** [comment]
Thanks a lot for letting me know this. I'll check the package against the Atom dev version you mentioned, and will release a fix asap!

**Comment by b3by** [comment]
Thank you again for the hint! Apparently I'm an idiot, too much Python programming and I forget to use `var` when switching back to JavaScript.

The issue should be fixed, I tested it against the master Atom code and it seems to work.
Cheerio!
