### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by wolfieman** [b3by/atom-clock#54]
*Stack Trace*
Any additional information, configuration or data that might be necessary to reproduce the issue.
TypeError: atom.tooltips.findTooltips is not a function
at AtomClockView.setTooltip (/home/wolfie/.atom/packages/atom-clock/lib/atom-clock-view.js:140:21)
at AtomClockView.initialize (/home/wolfie/.atom/packages/atom-clock/lib/atom-clock-view.js:19:10)
at AtomClockView.start (/home/wolfie/.atom/packages/atom-clock/lib/atom-clock-view.js:14:10)
at Object.consumeStatusBar (/home/wolfie/.atom/packages/atom-clock/lib/atom-clock.js:63:24)
at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:362:71)
at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:187:16)
at /usr/share/atom/resources/app.asar/src/package.js:157:32
at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
at /usr/share/atom/resources/app.asar/src/package.js:150:26
at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:147:34)
at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:550:34)
at /usr/share/atom/resources/app.asar/src/package-manager.js:531:29
at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:526:19)
at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:508:46)
at /usr/share/atom/resources/app.asar/src/atom-environment.js:792:28

**Comment by b3by** [comment]
Sorry for the late reply. I am not using the `ide-python` package, but even installing it did not make the bug reproducible for me: both packages work fine. I would need more details about your configuration I think.
Also, have you tried starting Atom in safe mode and activating these packages only? Is the bug still there?

**Comment by b3by** [comment]
Is this still happening?

**Comment by b3by** [comment]
Closing as not being followed up.
