### ISSUE TITLE
Uncaught TypeError: Cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by Akash98Sky** [b3by/atom-clock#59]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Ubuntu 18.04.1
**Thrown From**: [atom-clock](https://github.com/b3by/atom-clock) package 0.1.16

### Stack Trace

Uncaught TypeError: Cannot read property 'enable' of undefined

```
At /home/sky/.atom/packages/atom-clock/lib/atom-clock-view.js:140

TypeError: Cannot read property 'enable' of undefined
    at AtomClockView.setTooltip (/packages/atom-clock/lib/atom-clock-view.js:140:50)
    at /packages/atom-clock/lib/atom-clock-view.js:35:12
    at emitter.on (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:335221)
    at Function.simpleDispatch (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:1189772)
    at Emitter.emit (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:1191213)
    at Config.emitChangeEvent (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:337709)
    at Config.endTransaction (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:332480)
    at Config.transact (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:332099)
    at Config._resetSettings (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:333732)
    at Config.resetUserSettings (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:333499)
    at disposables.add.applicationDelegate.onDidChangeUserSettings.e (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:1:644526)
    at ipcMessageEmitter.on.t (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:1:660858)
    at Function.simpleDispatch (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:1189772)
    at Emitter.emit (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:1191213)
    at EventEmitter._ipcMessageEmitter.get_ipcRenderer.on (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:1:657482)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
colorblind-wombat-dark-syntax 0.6.0 
Hydrogen 2.6.0 
javascript-snippets 1.2.1 
teletype 0.13.3 
```

**Comment by b3by** [comment]
Thank you for reporting the issue. Unfortunately, I was not able to reproduce it on my system. Is it still present in the latest Atom version (1.35.1)?

**Comment by Akash98Sky** [comment]
Will check and report.

**Comment by b3by** [comment]
As there are no further updates on this, I will close.
