### ISSUE TITLE
failed to activate the status-bar package when atom-clock enabled

### ISSUE THREAD

**Issue by liuran** [b3by/atom-clock#60]
1. open Atom and and this error message happens

**Atom Version**: 1.12.8
**Electron Version**: 1.3.13
**System**: Mac OS X 10.14
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.1

### Stack Trace

Failed to activate the status-bar package

```
At atom.tooltips.findTooltips is not a function

TypeError: atom.tooltips.findTooltips is not a function
    at AtomClockView.setTooltip (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock-view.js:142:21)
    at AtomClockView.initialize (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock-view.js:19:10)
    at AtomClockView.start (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock-view.js:14:10)
    at Object.consumeStatusBar (/Users/liuran/.atom/packages/atom-clock/lib/atom-clock.js:63:24)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:362:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:187:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28
```

**Comment by KeithETruesdell** [comment]
I just started to get the same error.  
I had it installed from about 2 years ago, just accidentally changed a file in the package and couldn't get it back.  Uninstalled it and reinstalled it and just got the same message.  Newer Atom version different OS, same issues.
 
Atom Version: .1.34.0
Electron Version: 2.0.16
System: Windows 10 x64
Chrome: 61.0.3163.100
Node: 8.9.3

**Comment by b3by** [comment]
Thank you for reporting the issue guys. Is it still present on the newest Atom version (1.35.1)?

**Comment by KeithETruesdell** [comment]
It does not seem to be an issue in the newest version of Atom, (1.35.1) on Win 10 x64 for me.
Thank you.

**Comment by b3by** [comment]
Thank you for the follow up!
