### ISSUE TITLE
Failed to load the atom-clock package

### ISSUE THREAD

**Issue by Whysosry76** [b3by/atom-clock#62]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-clock](https://github.com/b3by/atom-clock) package 0.1.16

### Stack Trace

Failed to load the atom-clock package

```
At file:///C:/Users/PANZER/.atom/packages/atom-clock/lib/atom-clock-view.js: Unexpected token (164:0)

SyntaxError: file:///C:/Users/PANZER/.atom/packages/atom-clock/lib/atom-clock-view.js: Unexpected token (164:0)
[0m
[32m}[39m
[0m
    at Parser.pp.raise (/app.asar/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/app.asar/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseIdent (/app.asar/node_modules/babylon/lib/parser/expression.js:818:10)
    at Parser.pp.parsePropertyName (/app.asar/node_modules/babylon/lib/parser/expression.js:694:135)
    at Parser.pp.parseClass (/app.asar/node_modules/babylon/lib/parser/statement.js:559:10)
    at Parser.pp.parseExprAtom (/app.asar/node_modules/babylon/lib/parser/expression.js:405:19)
    at Parser.parseExprAtom (/app.asar/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/app.asar/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/app.asar/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/app.asar/node_modules/babylon/lib/parser/expression.js:163:19)
    at Parser.pp.parseMaybeConditional (/app.asar/node_modules/babylon/lib/parser/expression.js:145:19)
    at Parser.pp.parseMaybeAssign (/app.asar/node_modules/babylon/lib/parser/expression.js:112:19)
    at Parser.pp.parseExport (/app.asar/node_modules/babylon/lib/parser/statement.js:682:21)
    at Parser.parseExport (/app.asar/node_modules/babylon/lib/plugins/flow.js:713:20)
    at Parser.pp.parseStatement (/app.asar/node_modules/babylon/lib/parser/statement.js:115:90)
    at Parser.parseStatement (/app.asar/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/app.asar/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/app.asar/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/app.asar/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/app.asar/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:574:40)
    at File.parseCode (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:691:20)
    at /app.asar/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/app.asar/node_modules/babel-core/lib/transformation/file/index.js:639:16)
    at Pipeline.transform (/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.e.compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:576828)
    at Object.compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:573627)
    at compileFileAtPath (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:147800)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150197)
    at Module.load (module.js:561:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-material-syntax undefined 
atom-material-ui 2.1.3 
editorconfig 2.3.0 
firacode 0.3.0 
gtk-dark-theme 0.1.4 
symbols-list 2.5.3 
```

**Comment by b3by** [comment]
Thank you for reporting the issue. I was not able to reproduce the issue on my environment. Does the issue still appear if you start atom in safe mode?

**Comment by b3by** [comment]
As there are no further updates on this, I will close.
