### ISSUE TITLE
Cannot find module 'jquery

### ISSUE THREAD

**Issue by GreenLondon** [b3by/atom-clock#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Pro
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.1

### Stack Trace

Failed to activate the status-bar package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\User\.atom\packages\atom-clock\node_modules\space-pen\lib\space-pen.js:9:18)
    at Object.<anonymous> (C:\Users\User\.atom\packages\atom-clock\node_modules\space-pen\lib\space-pen.js:634:4)
    at Module._compile (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\User\.atom\packages\atom-clock\node_modules\atom-space-pen-views\lib\main.js:4:10)
    at Object.<anonymous> (C:\Users\User\.atom\packages\atom-clock\node_modules\atom-space-pen-views\lib\main.js:22:4)
    at Module._compile (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/atom-clock/lib/atom-clock-view.coffee:1:10)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/atom-clock/lib/atom-clock-view.coffee:1:1)
    at Module._compile (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\User\AppData\Local\atom\app-1.12.7\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-clock, v0.0.8 (inactive)
emmet, v2.4.3 (inactive)
highlight-line, v0.11.1 (inactive)
minimap, v4.25.7 (inactive)
qolor, v0.4.1 (inactive)
wordpress-api, v1.2.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by b3by** [comment]
I'm running the same versions of Atom, Electron and status-bar, but I don't get this issue. I'm checking into that, will try to solve it ASAP.
Cheers!

**Comment by b3by** [comment]
Commit 9e2af3621086f7a7efaeacdbd896654daf208786 should fix this, since `atom-space-pen-views` is no longer required. Closing.
